project:
  workdir: /proj/snic2022-6-176/nobackup/private/human_placenta/pcos
  project_name: pcos_placenta
  h5dir: /proj/snic2022-6-176/nobackup/private/human_placenta/pcos/output/cellbender
  datadir: /proj/snic2022-6-176/nobackup/private/human_placenta/pcos/output/data
files:
  info: /proj/snic2022-6-176/nobackup/private/human_placenta/pcos/info/pcos_placenta_info.txt
